CREATE DATABASE WISEINVEST;

USE WISEINVEST;

CREATE TABLE TB_USUARIO (ID_USUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
EMAIL_USUARIO VARCHAR (80) NOT NULL UNIQUE,
SENHA_USUARIO VARCHAR (20) NOT NULL,
DTA_CADASTRO_USUARIO DATETIME DEFAULT NOW(),
STATUS_USUARIO VARCHAR (40) NOT NULL);

CREATE TABLE TB_ADM (ID_ADM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,	
NOME_ADM VARCHAR (120) NOT NULL UNIQUE,
EMAIL_ADM VARCHAR (80) NOT NULL UNIQUE,
SENHA_ADM VARCHAR (20) NOT NULL UNIQUE,
STATUS_ADM VARCHAR (60) NOT NULL);

CREATE TABLE TB_EMPREENDEDOR (ID_EMPREENDEDOR INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_USUARIO INT NOT NULL,
NOME_EMPREENDEDOR VARCHAR (80) NOT NULL UNIQUE,
CPF_EMPREENDEDOR CHAR (14) NOT NULL UNIQUE,
CNPJ_EMPREENDEDOR CHAR (19) NOT NULL UNIQUE,
CAPITAL_ATIVO NUMERIC (9,2),
FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO));

CREATE TABLE TB_ESTUDANTE (ID_ESTUDANTE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_USUARIO INT NOT NULL,
NOME_ESTUDANTE VARCHAR (80) NOT NULL,
CPF_ESTUDANTE CHAR (14) NOT NULL UNIQUE,
INSTITUICAO_ESTUDANTE VARCHAR (60) NOT NULL,
MATRICULA_ESTUDANTE VARCHAR (20) NOT NULL,
CURSO_ESTUDANTE VARCHAR (30) NOT NULL,
AREA_ESTUDANTE VARCHAR (25) NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO (ID_USUARIO));

CREATE TABLE TB_PROJETOS_ACADEMICOS (ID_PROJETO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_ESTUDANTE INT NOT NULL,
NOME_PROJETO VARCHAR (40) NOT NULL UNIQUE,
AREA_PROJETO VARCHAR (25) NOT NULL,
DESCRICAO_PROJETO VARCHAR (255) NOT NULL,
CUSTO_ESTIMADO NUMERIC (7,2) NOT NULL,
PROPRIETARIOS_PROJETO INT DEFAULT 1,
STATUS_PROJETO VARCHAR (20) NOT NULL,
FOREIGN KEY (ID_ESTUDANTE) REFERENCES TB_ESTUDANTE (ID_ESTUDANTE));

CREATE TABLE TB_STARTUP (ID_STARTUP INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_EMPREENDEDOR INT NOT NULL
ID_PROJETO INT NOT NULL,
NOME_STARTUP VARCHAR (60) NOT NULL UNIQUE,
CAPITAL_STARTUP NUMERIC (7,2) NOT NULL,
AREA_STARTUP VARCHAR (25) NOT NULL,
CNPJ_STARTUP CHAR (19) NOT NULL UNIQUE,
RAZAO_SOCIAL_STARTUP VARCHAR (60) NOT NULL UNIQUE,
SOCIOS_STARTUP INT DEFAULT 1,
STATUS_STARTUP VARCHAR (20) NOT NULL,
FOREIGN KEY (ID_EMPREENDEDOR) REFERENCES TB_EMPREENDEDOR (ID_EMPREENDEDOR),
FOREIGN KEY (ID_PROJETO) REFERENCES TB_PROJETOS_ACADEMICOS (ID_PROJETO));

CREATE TABLE TB_EMPRESA (ID_EMPRESA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ID_EMPREENDEDOR INT NOT NULL,
NOME_EMPRESA VARCHAR (60) NOT NULL UNIQUE,
CAPITAL_EMPRESA NUMERIC (9,2) NOT NULL,
CNPJ_EMPRESA CHAR (19) NOT NULL,
RAZAO_SOCIAL_EMPRESA VARCHAR (60) NOT NULL UNIQUE,
STATUS_EMPRESA VARCHAR (20) NOT NULL,
FOREIGN KEY (ID_EMPREENDEDOR) REFERENCES TB_EMPREENDEDOR (ID_EMPREENDEDOR));







